# Config for the final MSDS510 project
# CSV file name stuff
RawInputFile: ../data/raw/bad-drivers.csv
InterimUTF8File: ../data/interim/bad-drivers-utf-8.csv
OutputFile: ../data/processed/bad-drivers-processed.csv
RowToPrint: 23
ReportFile: ../reports/Bad_Drivers.md
